// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotesExtensionVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "NotesExtensionVS.9e373e3e-c050-4c5d-87c1-ac62b1651d95";
        public const string Name = "NotesExtensionVS";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
